package org.xrpl.xrpl4j.model.transactions;

public class TransactionResult {

  // tec
  String TEC = "tec";
  String TEC_CLAIM = TEC + "CLAIM";
  String TEC_CRYPTOCONDITION_ERROR = TEC + "CRYPTOCONDITION_ERROR";
  String TEC_DIR_FULL = TEC + "DIR_FULL";
  String TEC_DUPLICATE = TEC + "DUPLICATE";
  String TEC_DST_TAG_NEEDED = TEC + "DST_TAG_NEEDED";
  String TEC_EXPIRED = TEC + "EXPIRED";
  String TEC_FAILED_PROCESSING = TEC + "FAILED_PROCESSING";
  String TEC_FROZEN = TEC + "FROZEN";
  String TEC_HAS_OBLIGATIONS = TEC + "HAS_OBLIGATIONS";
  String TEC_INSUF_RESERVE_LINE = TEC + "INSUF_RESERVE_LINE";
  String TEC_INSUF_RESERVE_OFFER = TEC + "INSUF_RESERVE_OFFER";
  String TEC_INSUFF_FEE = TEC + "INSUFF_FEE";
  String TEC_INSUFFICIENT_RESERVE = TEC + "INSUFFICIENT_RESERVE";
  String TEC_INTERNAL = TEC + "INTERNAL";
  String TEC_INVARIANT_FAILED = TEC + "INVARIANT_FAILED";
  String TEC_KILLED = TEC + "KILLED";
  String TEC_NEED_MASTER_KEY = TEC + "NEED_MASTER_KEY";
  String TEC_NO_ALTERNATIVE_KEY = TEC + "NO_ALTERNATIVE_KEY";
  String TEC_NO_AUTH = TEC + "NO_AUTH";
  String TEC_NO_DST = TEC + "NO_DST";
  String TEC_NO_DST_INSUF_XRP = TEC + "NO_DST_INSUF_XRP";
  String TEC_NO_ENTRY = TEC + "NO_ENTRY";
  String TEC_NO_ISSUER = TEC + "NO_ISSUER";
  String TEC_NO_LINE = TEC + "NO_LINE";
  String TEC_NO_LINE_INSUF_RESERVE = TEC + "NO_LINE_INSUF_RESERVE";
  String TEC_NO_LINE_REDUNDANT = TEC + "NO_LINE_REDUNDANT";
  String TEC_NO_PERMISSION = TEC + "NO_PERMISSION";
  String TEC_NO_REGULAR_KEY = TEC + "NO_REGULAR_KEY";
  String TEC_NO_TARGET = TEC + "NO_TARGET";
  String TEC_OVERSIZE = TEC + "OVERSIZE";
  String TEC_OWNERS = TEC + "OWNERS";
  String TEC_PATH_DRY = TEC + "PATH_DRY";
  String TEC_PATH_PARTIAL = TEC + "PATH_PARTIAL";
  String TEC_TOO_SOON = TEC + "TOO_SOON";
  String TEC_UNFUNDED = TEC + "UNFUNDED";
  String TEC_UNFUNDED_ADD = TEC + "UNFUNDED_ADD";
  String TEC_UNFUNDED_PAYMENT = TEC + "UNFUNDED_PAYMENT";
  String TEC_UNFUNDED_OFFER = TEC + "UNFUNDED_OFFER";

  // tef codes
  String TEF = "tef";
  String TEF_ALREADY = TEF + "ALREADY";
  String TEF_BAD_ADD_AUTH = TEF + "BAD_ADD_AUTH";
  String TEF_BAD_AUTH = TEF + "BAD_AUTH";
  String TEF_BAD_AUTH_MASTER = TEF + "BAD_AUTH_MASTER";
  String TEF_BAD_LEDGER = TEF + "BAD_LEDGER";
  String TEF_BAD_QUORUM = TEF + "BAD_QUORUM";
  String TEF_BAD_SIGNATURE = TEF + "BAD_SIGNATURE";
  String TEF_CREATED = TEF + "CREATED";
  String TEF_EXCEPTION = TEF + "EXCEPTION";
  String TEF_FAILURE = TEF + "FAILURE";
  String TEF_INTERNAL = TEF + "INTERNAL";
  String TEF_INVARIANT_FAILED = TEF + "INVARIANT_FAILED";
  String TEF_MASTER_DISABLED = TEF + "MASTER_DISABLED";
  String TEF_MAX_LEDGER = TEF + "MAX_LEDGER";
  String TEF_NO_AUTH_REQUIRED = TEF + "NO_AUTH_REQUIRED";
  String TEF_NO_TICKET = TEF + "NO_TICKET";
  String TEF_NOT_MULTI_SIGNING = TEF + "NOT_MULTI_SIGNING";
  String TEF_PAST_SEQ = TEF + "PAST_SEQ";
  String TEF_TOO_BIG = TEF + "TOO_BIG";
  String TEF_WRONG_PRIOR = TEF + "WRONG_PRIOR";

  // tel codes
  String TEL = "tel";
  String TEL_BAD_DOMAIN = TEF + "BAD_DOMAIN";
  String TEL_BAD_PATH_COUNT = TEF + "BAD_PATH_COUNT";
  String TEL_BAD_PUBLIC_KEY = TEF + "BAD_PUBLIC_KEY";
  String TEL_CAN_NOT_QUEUE = TEF + "CAN_NOT_QUEUE";
  String TEL_CAN_NOT_QUEUE_BALANCE = TEF + "CAN_NOT_QUEUE_BALANCE";
  String TEL_CAN_NOT_QUEUE_BLOCKS = TEF + "CAN_NOT_QUEUE_BLOCKS";
  String TEL_CAN_NOT_QUEUE_BLOCKED = TEF + "CAN_NOT_QUEUE_BLOCKED";
  String TEL_CAN_NOT_QUEUE_FEE = TEF + "CAN_NOT_QUEUE_FEE";
  String TEL_CAN_NOT_QUEUE_FULL = TEF + "CAN_NOT_QUEUE_FULL";
  String TEL_FAILED_PROCESSING = TEF + "FAILED_PROCESSING";
  String TEL_INSUF_FEE_P = TEF + "INSUF_FEE_P";
  String TEL_LOCAL_ERROR = TEF + "LOCAL_ERROR";
  String TEL_NO_DST_PARTIAL = TEF + "NO_DST_PARTIAL";

  //tem codes
  String TEM = "tem";
  String TEM_BAD_AMOUNT = TEM + "BAD_AMOUNT";
  String TEM_BAD_AUTH_MASTER = TEM + "BAD_AUTH_MASTER";
  String TEM_BAD_CURRENCY = TEM + "BAD_CURRENCY";
  String TEM_BAD_EXPIRATION = TEM + "BAD_EXPIRATION";
  String TEM_BAD_FEE = TEM + "BAD_FEE";
  String TEM_BAD_ISSUER = TEM + "BAD_ISSUER";
  String TEM_BAD_LIMIT = TEM + "BAD_LIMIT";
  String TEM_BAD_OFFER = TEM + "BAD_OFFER";
  String TEM_BAD_PATH = TEM + "BAD_PATH";
  String TEM_BAD_PATH_LOOP = TEM + "BAD_PATH_LOOP";
  String TEM_BAD_SEND_XRP_LIMIT = TEM + "BAD_SEND_XRP_LIMIT";
  String TEM_BAD_SEND_XRP_MAX = TEM + "BAD_SEND_XRP_MAX";
  String TEM_BAD_SEND_XRP_NO_DIRECT = TEM + "BAD_SEND_XRP_NO_DIRECT";
  String TEM_BAD_SEND_XRP_PARTIAL = TEM + "BAD_SEND_XRP_PARTIAL";
  String TEM_BAD_SEND_XRP_PATHS = TEM + "BAD_SEND_XRP_PATHS";
  String TEM_BAD_SEQUENCE = TEM + "BAD_SEQUENCE";
  String TEM_BAD_SIGNATURE = TEM + "BAD_SIGNATURE";
  String TEM_BAD_SRC_ACCOUNT = TEM + "BAD_SRC_ACCOUNT";
  String TEM_BAD_TRANSFER_RATE = TEM + "BAD_TRANSFER_RATE";
  String TEM_CANNOT_PREAUTH_SELF = TEM + "CANNOT_PREAUTH_SELF";
  String TEM_DST_IS_SRC = TEM + "DST_IS_SRC";
  String TEM_DST_NEEDED = TEM + "DST_NEEDED";
  String TEM_INVALID = TEM + "INVALID";
  String TEM_INVALID_COUNT = TEM + "INVALID_COUNT";
  String TEM_INVALID_FLAG = TEM + "INVALID_FLAG";
  String TEM_MALFORMED = TEM + "MALFORMED";
  String TEM_REDUNDANT = TEM + "REDUNDANT";
  String TEM_REDUNDANT_SEND_MAX = TEM + "REDUNDANT_SEND_MAX";
  String TEM_RIPPLE_EMPTY = TEM + "RIPPLE_EMPTY";
  String TEM_BAD_WEIGHT = TEM + "BAD_WEIGHT";
  String TEM_BAD_SIGNER = TEM + "BAD_SIGNER";
  String TEM_BAD_QUORUM = TEM + "BAD_QUORUM";
  String TEM_UNCERTAIN = TEM + "UNCERTAIN";
  String TEM_UNKNOWN = TEM + "UNKNOWN";
  String TEM_DISABLED = TEM + "DISABLED";

  // ter codes
  String TER = "ter";
  @Deprecated
  String TER_FUNDS_SPENT = TER + "FUNDS_SPENT";
  String TER_INSUF_FEE_B = TER + "INSUF_FEE_B";
  String TER_LAST = TER + "LAST";
  String TER_NO_ACCOUNT = TER + "NO_ACCOUNT";
  String TER_NO_AUTH = TER + "NO_AUTH";
  String TER_NO_LINE = TER + "NO_LINE";
  String TER_NO_RIPPLE = TER + "NO_RIPPLE";
  String TER_OWNERS = TER + "OWNERS";
  String TER_PRE_SEQ = TER + "PRE_SEQ";
  String TER_PRE_TICKET = TER + "PRE_TICKET";
  String TER_RETRY = TER + "RETRY";
  String TER_QUEUED = TER + "QUEUED";

  // tes codes
  String TES = "tes";
  String TES_SUCCESS = TES + "SUCCESS";
}
