name: xrpl4j-CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.8]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Set up Java 8
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache mvn dependencies
        uses: actions/cache@v2
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
      - name: Build
        run: mvn dependency:go-offline install
      - if: matrix.java == "1.8"
        - name: Upload to Codecov
          uses: codecov/codecov-action@v1.0.15
