name: xrpl4j-CI


on:
  push:
  pull_request:
    types: [assigned]
jobs:
  build_java8:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Set up Java 8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache mvn dependencies
        uses: actions/cache@v2
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Build
        run: mvn dependency:go-offline install
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.0.15

  build_android:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Set up Android
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Cache mvn dependencies
        uses: actions/cache@v2
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Build
        run: mvn dependency:go-offline install -Dmaven.javadoc.skip=true -Pandroid

  build_other_java:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # test against each major Java version
        java: [ 9, 10, 11, 12, 13, 14, 15, 16, 17 ]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Set up Java version
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache mvn dependencies
        uses: actions/cache@v2
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Build
        run: mvn dependency:go-offline install -Dmaven.javadoc.skip=true

  build_open_jdk_non_us:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Set up Adopt OpenJDK Hotspot 16
      - name: Set up OpenJDK 16
        uses: actions/setup-java@v1
        with:
          distribution: adopt
          java-version: 16
      - name: Cache mvn dependencies
        uses: actions/cache@v2
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      # Maven install with JVM locale = de_DE
      - name: Build
        run: mvn dependency:go-offline install -Dmaven.javadoc.skip=true -DargLine="-Duser.language=de -Duser.country=DE"

  build_devnet_its:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Set up Java 8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache mvn dependencies
        uses: actions/cache@v2
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Build
        run: mvn dependency:go-offline install -Dmaven.javadoc.skip=true -DuseDevnet

  build_testnet_its:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # Set up Java 8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache mvn dependencies
        uses: actions/cache@v2
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Build
        run: mvn dependency:go-offline install -Dmaven.javadoc.skip=true -DuseTestnet